### ISSUE TITLE
Why are we specifying interrupts two times in the powerdown.ino script.

### ISSUE THREAD

**Issue by AdarshPan** [futureshocked/TE-Arduino-SbS-Getting-Serious#1]
Please refer to the below script of this repo.
https://github.com/futureshocked/TE-Arduino-SbS-Getting-Serious/blob/master/_2140b_-_powerdown/_2140b_-_powerdown.ino

Why are we specifying the interrupts in the setup() method as well as the sleepNow() method??

I think mentioning it in the setup() method itself is enough .

Best Regards ,
Adarsh

**Comment by futureshocked** [comment]
Hi Adarsh,

you are right, the attachInterrupt in the setup function is redundant.

I have removed it in the sketch.
